// Generated by CoffeeScript 1.4.0

/*
Table Filtering and Search for jQuery
version: 0.1.1

Licensed under the MIT:
http://www.opensource.org/licenses/mit-license.php

Copyright 2013 Ryan McGeary
*/


(function() {
  var $;

  $ = jQuery;

  $.fn.sieve = function(options) {
    var compact;
    compact = function(array) {
      var item, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        item = array[_i];
        if (item) {
          _results.push(item);
        }
      }
      return _results;
    };
    return this.each(function() {
      var searchBar, settings, table;
      table = $(this);
      settings = $.extend({
        searchInput: null,
        searchTemplate: "<div><label>Search: <input type='text'></label></div>",
        rowSelector: "tr:not(:has('th'))",
        cellSelector: "td"
      }, options);
      if (!settings.searchInput) {
        searchBar = $(settings.searchTemplate);
        settings.searchInput = searchBar.find("input");
        table.before(searchBar);
      }
      return settings.searchInput.on("keyup", function() {
        var query, rows;
        query = compact($(this).val().toLowerCase().split(/\s+/));
        rows = table.find(settings.rowSelector);
        return rows.each(function() {
          var cells, matches, q, row, text, _i, _len;
          row = $(this);
          cells = row.find(settings.cellSelector);
          text = cells.text().toLowerCase();
          matches = true;
          for (_i = 0, _len = query.length; _i < _len; _i++) {
            q = query[_i];
            matches && (matches = text.indexOf(q) >= 0);
          }
          return row.toggle(matches);
        });
      });
    });
  };

}).call(this);
